#:schema node_modules/wrangler/config-schema.json
name = "boilerplate-node"
main = ".next/standalone/worker.mjs"
assets = ".next/assets"
compatibility_date = "2024-07-01"
compatibility_flags = ["experimental:nodejs_compat_v2"]
workers_dev = true
minify = false

[alias]
"critters" = "./scripts/shim-throw.mjs"
"@opentelemetry/api" = "./scripts/shim-throw.mjs"
"next/dist/compiled/@ampproject/toolbox-optimizer" = "./scripts/shim-throw.mjs"
"next/dist/experimental/testmode/server" = "./scripts/shim-throw.mjs"
"next/dist/compiled/ws" = "./scripts/shim-throw.mjs"
# "next/dist/compiled/node-html-parser" = "./scripts/shim-throw.mjs"
"@next/env" = "./scripts/shim-throw.mjs"
"next/dist/compiled/jsonwebtoken" = "./scripts/shim-throw.mjs"
"./cjs/react-dom-server-legacy.browser.development.js" = "./scripts/shim-throw.mjs"
"./cjs/react-dom-server.browser.development.js" = "./scripts/shim-throw.mjs"
"./cjs/react.development.js" = "./scripts/shim-throw.mjs"
"./cjs/react-jsx-runtime.development.js" = "./scripts/shim-throw.mjs"
